// src/config.js
export const uiTextConfig = {
    en: {
        supportAdmin: "Support Admin",
        generator: "Generator",
        settings: "Settings",
        contentType: "Content Type",
        singlePost: "Single Post",
        carousel: "Carousel",
        productName: "Product Name",
        productNamePlaceholder: "e.g., AnoTech Ergonomic Chair",
        productDesc: "Product Description",
        productDescPlaceholder: "Explain the main features, advantages, and benefits...",
        languageStyle: "Language Style",
        targetAudience: "Target Audience",
        hookType: "Hook Type",
        numberOfScripts: "Number of Scripts",
        numberOfSlides: "Number of Slides",
        generateButton: "Generate Script with AI",
        generatingButton: "Generating...",
        saveAsPdf: "Save as PDF",
        downloadAsDocx: "Download as .docx",
        outputPlaceholderTitle: "Your generated scripts will appear here.",
        outputPlaceholderSubtitle: "Fill out the form and click \"Generate Script with AI\" to start.",
        errorTitle: "Failed to Generate Scripts",
        tryAgain: "Try Again",
        editAndRegenerate: "Edit & Regenerate",
        problemCallout: "Problem Call-Out",
        storytellingBody: "Storytelling Body",
        callToAction: "Call To Action",
        settingsTitle: "Settings",
        apiSettings: "API Settings",
        apiSettingsDesc: "Manage your API key to access external AI tools.",
        apiMode: "API Mode",
        apiModeDefault: "Use AnoTechHub's Default Key",
        apiModeCustom: "Use Your Own API Key",
        yourApiKey: "Your Gemini API Key",
        apiKeyPlaceholder: "Enter your API key here...",
        saveApiSettings: "Save API Settings",
        systemPrompt: "System Instruction Prompt",
        systemPromptDesc: "This prompt will guide the AI's personality and response style.",
        promptInstruction: "Prompt Instruction",
        saveChanges: "Save Changes",
        activePrompt: "Active Prompt Instruction",
        downloadStarted: "Download Started!",
        thankYouMessage: "Thank you for using the Anotechhub generator. Have a great day!",
        close: "Close",
        apiKeyApplied: "API Key Applied!",
        apiKeyAppliedMessage: "Your API key has been saved and will be used for future requests.",
        gotIt: "Got it",
        editAndRegenerateModalTitle: "Edit & Regenerate",
        originalVersion: "Original Version",
        newVersion: "New Version",
        aiIsWorking: "AI is working...",
        newVersionPlaceholder: "New version will appear here.",
        revisionInstructions: "Revision Instructions (Free Form)",
        revisionPlaceholder: "e.g., Make it funnier, target teenagers, use more formal language...",
        regenerate: "Regenerate",
        useThisVersion: "Use This Version",
        apiKeyWarning: "Note: This is a shared key and may have limitations. For the best experience, we highly recommend using your own API key.",
    },
    id: {
        supportAdmin: "Dukungan Admin",
        generator: "Generator",
        settings: "Pengaturan",
        contentType: "Jenis Konten",
        singlePost: "Single Post",
        carousel: "Carousel",
        productName: "Nama Produk",
        productNamePlaceholder: "Contoh: Kursi Ergonomis AnoTech",
        productDesc: "Deskripsi Produk",
        productDescPlaceholder: "Jelaskan fitur utama, keunggulan, dan manfaat produk Anda...",
        languageStyle: "Gaya Bahasa",
        targetAudience: "Target Audience",
        hookType: "Jenis Hook",
        numberOfScripts: "Jumlah Script",
        numberOfSlides: "Jumlah Slide",
        generateButton: "Buat Script dengan AI",
        generatingButton: "Membuat...",
        saveAsPdf: "Simpan sebagai PDF",
        downloadAsDocx: "Unduh sebagai .docx",
        outputPlaceholderTitle: "Skrip yang Anda buat akan muncul di sini.",
        outputPlaceholderSubtitle: "Isi formulir dan klik \"Buat Script dengan AI\" untuk memulai.",
        errorTitle: "Gagal Membuat Skrip",
        tryAgain: "Coba Lagi",
        editAndRegenerate: "Edit & Regenerasi",
        problemCallout: "Problem Call-Out",
        storytellingBody: "Isi Cerita",
        callToAction: "Call To Action",
        settingsTitle: "Pengaturan",
        apiSettings: "Pengaturan API",
        apiSettingsDesc: "Kelola kunci API Anda untuk mengakses tool AI eksternal.",
        apiMode: "Mode API",
        apiModeDefault: "Gunakan Kunci Default AnoTechHub",
        apiModeCustom: "Gunakan Kunci API Sendiri",
        yourApiKey: "Kunci API Gemini Anda",
        apiKeyPlaceholder: "Masukkan kunci API Anda di sini...",
        saveApiSettings: "Simpan Pengaturan API",
        systemPrompt: "Prompt Instruksi Sistem",
        systemPromptDesc: "Prompt ini akan mengarahkan kepribadian dan gaya respons AI.",
        promptInstruction: "Instruksi Prompt",
        saveChanges: "Simpan Perubahan",
        activePrompt: "Instruksi Prompt Aktif",
        downloadStarted: "Unduhan Dimulai!",
        thankYouMessage: "Terima kasih sudah menggunakan generator Anotechhub. Semoga harimu menyenangkan!",
        close: "Tutup",
        apiKeyApplied: "Kunci API Diterapkan!",
        apiKeyAppliedMessage: "Kunci API Anda telah disimpan dan akan digunakan untuk permintaan berikutnya.",
        gotIt: "Mengerti",
        editAndRegenerateModalTitle: "Edit & Regenerasi",
        originalVersion: "Versi Asli",
        newVersion: "Versi Baru",
        aiIsWorking: "AI sedang bekerja...",
        newVersionPlaceholder: "Versi baru akan muncul di sini.",
        revisionInstructions: "Instruksi Revisi (Bebas)",
        revisionPlaceholder: "Contoh: Buat lebih lucu, targetkan untuk remaja, gunakan bahasa yang lebih formal...",
        regenerate: "Regenerasi",
        useThisVersion: "Gunakan Versi Ini",
        apiKeyWarning: "Catatan: Kunci ini digunakan bersama dan mungkin memiliki batasan. Untuk pengalaman terbaik, kami sangat menyarankan menggunakan kunci API Anda sendiri.",
    }
};

export const systemPrompts = {
    en: "You are an expert AI copywriter specializing in creating engaging affiliate marketing scripts. Generate creative and persuasive responses based on the provided product details.",
    id: "Anda adalah seorang copywriter AI yang ahli dalam membuat skrip promosi afiliasi. Buatlah respons yang kreatif dan persuasif sesuai dengan detail produk yang diberikan."
};